version: '3.4'

services:
  db:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5432:5432 
    environment:
      POSTGRES_DB: foodpool
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
